### ISSUE TITLE
Dar de alta un usuario en la biblioteca

### ISSUE THREAD

**Issue by DerekLopezGarcia** [DerekLopezGarcia/ed-digital-library-Derek#1]
## Descripción
El cliente no pide poder dar de alta un usuario para poder reservar recursos digitales

## Implementación
- Crear una clase que modele que es un usuario
- Crear un caso de uso que para dar de alta el usuario
-  Crear un repositorio para gestionar las fuentes de datos
- Crear una fuente de datos local para guardar los datos del usuario en un fichero
- Crear una opción en el menú para dar de alta al usuario  

## Definición de hecho
- [x] Se muestra en el menú principal el dar de alta un usuario
- [x] Se muestra un formulario para recoger los datos del usuario
- [x] Se guardan los datos del usuario en el fichero

**Comment by BorjaJG** [comment]
Hola Derek,

¡Gracias por marcar la tarea como completada con éxito! ✅

Quería informarte que hemos implementado una nueva plantilla 📝 para el uso en este tipo de tareas. Adjunto a este mensaje te envío la plantilla para que puedas utilizarla en futuros Issues.

Agradecería mucho si pudieras aplicarla en tus próximas tareas. Esto nos ayudará a mantener un estándar de calidad y consistencia en nuestro trabajo.

Gracias de nuevo por tu contribución y por seguir mejorando nuestro proceso. ¡Sigue así!

Saludos, Borja
------------------
Plantilla de Issues  --->📝 https://github.com/BorjaJG/ed-digital-library/issues/3#issue-2244261293
